device:       cuda:0
robot_name:   leap_hand
scene_id:     scene_0000
seed:         2
evaluator:    SimulationEvaluator
headless:     True
batch_size:   100
overwrite:    1
strategy:     ours
save_path:    IBSGrasp/data
first_run:    True
scene_cfg_path:   IBSGrasp/conf/scene.yaml
