
# Scene
scene:
  scene_id: 0
  view_id:  0
  scene_pc_N: 40000
  dataset:  graspnet

hand:
  hand_name: dex2leap

# Stage 1 parameters
stage1:
  grasp_num:  16

# Stage 2 parameters
stage2:
  steps: 50
  las_model_path: "LASDiffusion/results/LEAP_dif/recent/last.ckpt"

# Stage 3 parameters
stage3:
  parallel_num: 5
  filt_or_not: 1
  cone_viz_num: 0
  cone_mu: 1
  hand_asset_path: "PoseOptimize/hand_assets"
  
  max_iters: 100
  lr: 5e-3
  lr_decay: 0.9
  lr_decay_every: 20
  inter_num_step: 20

# Data parameters
data:
  num_view: 1
  pc_root_path: "/media/matthew_zy/Data3/scene_pc"
  obj_root: "Assets/objects/graspnet"
  pose_save_path: "Experiments/poses"
  traj_save_path: "Experiments/traj"
  gt_root: "Data/IBS"

# Other parameters
others:
  device: "cuda:0"
  logs_path: "logs"
  
  vis_ibs:        0
  vis_result_h:   0
  vis_result_c:   0
  vis_result_w:   0

  save_results:   0
  save_traj_num:  0

  stage_1_use_gt: 1
  stage_2_use_gt: 0
  best_only:      false
  